version: "3"
services:
  clash:
    image: crpi-cnazxqmg4avmg4fq.cn-beijing.personal.cr.aliyuncs.com/ronghuaxueleng/clash:latest
    container_name: clash
    ports:
      - 7890:7890 # mixed-port
      - 9090:9090 # restful api port
    environment:
      - CONF_URL=https://proxy.v2gh.com/https://raw.githubusercontent.com/ronghuaxueleng/get_v2/refs/heads/main/pub/NoMoreWalls.yaml
      - EXTERNAL_BIND=0.0.0.0
      - EXTERNAL_PORT=9090
      - TZ=Aisa/Shanghai
      - DEFAULT_BACKEND=http://192.168.10.13:9090
    volumes: []
    depends_on: []
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=Tool
      - homepage.name=Clash
      - homepage.icon=clash.png
      - homepage.href=http://192.168.10.13:9090
      - homepage.description=Clash Dashboard

